FROM golang:1.18.4-bullseye AS builder

WORKDIR /gg-manager

COPY go.mod go.sum /gg-manager/
RUN go mod download

COPY . /gg-manager
RUN go build -o main ./cmd/gg-manager

FROM gcr.io/distroless/base-debian11
USER nonroot:nonroot

COPY --chown=nonroot:nonroot --from=builder /gg-manager/main /main

ENTRYPOINT ["/main"]
